### PR TITLE
Updated inferno package versions to 1.3.1 stable

### PR DESCRIPTION
**Pull request by wagerfield**
Inferno 1.3.1 stable was finally released today. 

This PR updates the `styletron-inferno` package versions of `inferno` to 1.3.1.

### CODE REVIEW

**Comment by wagerfield** [comment]
Once this is merged, could you please publish to npm? I would really appreciate being able to use this in my projects :)

**Comment by rtsao** [comment]
Nice! I was just about to do this :)

FWIW I think `1.3.1` satisfies `^1.3.0-rc.3` so you should still be able to use this...

**Comment by wagerfield** [comment]
Thanks a million for publishing really appreciate it :)

**Comment by rtsao** [comment]
Published new version of docs as well (with styletron-inferno): http://styletron.js.org/

**Comment by wagerfield** [comment]
Saw that, thank you!

**Pull request merged**
